export enum CustomError{
    NOT_FOUND = "NOT_FOUND",
    ALREADY_EXISTS = "ALREADY_EXISTS",
    NOT_ALLOWED = "NOT_ALLOWED",
    UNEXPECTED = "UNEXPECTED",
    WRONG_CREDENTIALS = "WRONG_CREDENTIALS"
}